---
Metrics/LineLength:                  { Enabled: false }
Metrics/AbcSize:                     { Enabled: false }
Metrics/MethodLength:                { Enabled: false }
Style/Documentation:                 { Enabled: false }
Naming/MemoizedInstanceVariableName: { Enabled: false }
